FROM node:18-bullseye-slim
ENV DYNAMO_PORT=
ENV DYNAMO_ENDPOINT=
ENV AWS_REGION=us-west-2

RUN npm i -g npm \
  && npm i -g dynamodb-admin

EXPOSE ${DYNAMO_PORT}

CMD ["sh", "-c", "dynamodb-admin -p ${DYNAMO_PORT}"]

